# Goal: statistical-summary

In [120]:
""" 
Goal: statistical-summary
Author: Rudra Prasad Bhuyan
Date: 10-10-2026 12:43 IST
"""

' \nGoal: statistical-summary\nAuthor: Rudra Prasad Bhuyan\nDate: 10-10-2026 12:43 IST\n'

In [121]:
!pip install itables -q

In [122]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
from itables import show

In [123]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-02\data\lev-02_merged.parquet"
pdf = pl.scan_parquet(path)

In [124]:
pdf.collect_schema()

Schema([('Survey_Name', String),
        ('Year', String),
        ('FSU_Serial_No', String),
        ('Sector', String),
        ('State', String),
        ('NSS_Region', String),
        ('District', String),
        ('Stratum', String),
        ('Sub_stratum', String),
        ('Panel', String),
        ('Sub_sample', String),
        ('FOD_Sub_Region', String),
        ('Sample_SU_No', String),
        ('Sample_Sub_Division_No', String),
        ('Second_Stage_Stratum_No', String),
        ('Sample_Household_No', String),
        ('Questionnaire_No', String),
        ('Level', String),
        ('Person_Serial_No', String),
        ('Relation_to_Head', String),
        ('Gender', String),
        ('Age', String),
        ('Marital_Status', String),
        ('Education_Level', String),
        ('Years_of_Education', String),
        ('Used_Internet_Last_30_Days', String),
        ('Days_Away_From_Home_Last_30_Days', String),
        ('Meals_Usually_Taken_Per_Day', String),
        ('Meals_From_School', String),
        ('Meals_From_Employer', String),
        ('Meals_Other', String),
        ('Meals_On_Payment', String),
        ('Meals_At_Home', String),
        ('Revisit_Status', String),
        ('FDQ_Original_Member', String),
        ('Multiplier', Int64)])

# Useful Variables

In [125]:
lev_02_hh = [ 'Revisit_Status', 'FDQ_Original_Member', 'Multiplier']

lev_02_food = ['Meals_Usually_Taken_Per_Day','Meals_From_School',
               'Meals_From_Employer','Meals_Other',
               'Meals_On_Payment','Meals_At_Home']

lev_02_digital = ['Used_Internet_Last_30_Days']

lev_02__behavior = ['Days_Away_From_Home_Last_30_Days']

lev_02_user = ['FSU_Serial_No', 'Relation_to_Head','Gender',
               'Age', 'Marital_Status', 
               'Education_Level', 'Years_of_Education']

In [126]:
lev_02_cols = (
    lev_02_hh
    + lev_02_food
    + lev_02_digital
    + lev_02__behavior
    + lev_02_user
)

In [127]:
df = pdf.select(lev_02_cols)

In [128]:
df

In [129]:
df.head(2).collect()

shape: (2, 18)
┌────────────┬────────────┬────────────┬────────────┬───┬─────┬────────────┬───────────┬───────────┐
│ Revisit_St ┆ FDQ_Origin ┆ Multiplier ┆ Meals_Usua ┆ … ┆ Age ┆ Marital_St ┆ Education ┆ Years_of_ │
│ atus       ┆ al_Member  ┆ ---        ┆ lly_Taken_ ┆   ┆ --- ┆ atus       ┆ _Level    ┆ Education │
│ ---        ┆ ---        ┆ i64        ┆ Per_Day    ┆   ┆ str ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ ---        ┆   ┆     ┆ str        ┆ str       ┆ str       │
│            ┆            ┆            ┆ str        ┆   ┆     ┆            ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═════╪════════════╪═══════════╪═══════════╡
│ 1          ┆ 1          ┆ 153083     ┆ 3          ┆ … ┆ 58  ┆ 2          ┆ 12        ┆ 15        │
│ 1          ┆ 1          ┆ 153083     ┆ 3          ┆ … ┆ 47  ┆ 2          ┆ 05        ┆ 9         │
└────────────┴────────────┴────────────┴────────────┴───┴─────┴────────────┴───────────┴───────────┘

In [130]:
df = df.with_columns(
    [pl.col(col).cast(pl.Int32, strict=False) for col in lev_02_cols]
)

In [131]:
unique_counts = df.select(pl.all().n_unique()).collect()
unique_counts

shape: (1, 18)
┌────────────┬────────────┬────────────┬────────────┬───┬─────┬────────────┬───────────┬───────────┐
│ Revisit_St ┆ FDQ_Origin ┆ Multiplier ┆ Meals_Usua ┆ … ┆ Age ┆ Marital_St ┆ Education ┆ Years_of_ │
│ atus       ┆ al_Member  ┆ ---        ┆ lly_Taken_ ┆   ┆ --- ┆ atus       ┆ _Level    ┆ Education │
│ ---        ┆ ---        ┆ u32        ┆ Per_Day    ┆   ┆ u32 ┆ ---        ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆            ┆ ---        ┆   ┆     ┆ u32        ┆ u32       ┆ u32       │
│            ┆            ┆            ┆ u32        ┆   ┆     ┆            ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═════╪════════════╪═══════════╪═══════════╡
│ 3          ┆ 2          ┆ 23567      ┆ 5          ┆ … ┆ 112 ┆ 4          ┆ 12        ┆ 23        │
└────────────┴────────────┴────────────┴────────────┴───┴─────┴────────────┴───────────┴───────────┘

In [132]:
unique_counts = df.select(pl.all().n_unique()).collect()

categorical_cols = []
numerical_cols = []

for col in df.columns:
    if unique_counts[col][0] <13:
        categorical_cols.append(col)
    else:
        numerical_cols.append(col)

C:\Users\Rudra\AppData\Local\Temp\ipykernel_9736\3703037397.py:6: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  for col in df.columns:

In [133]:
stats = df.select(numerical_cols).describe()
show(stats.to_pandas().T)

In [136]:
for col in categorical_cols:
    print(col)
    counts = df.select(pl.col(col).value_counts(sort=True)).collect()
    show(counts.unnest(col))

Revisit_Status

FDQ_Original_Member

Meals_Usually_Taken_Per_Day

Used_Internet_Last_30_Days

Relation_to_Head

Gender

Marital_Status

Education_Level