# Goal: statistical-summary

In [120]:
""" 
Goal: statistical-summary
Author: Rudra Prasad Bhuyan
Date: 10-10-2026 12:43 IST
"""

' \nGoal: statistical-summary\nAuthor: Rudra Prasad Bhuyan\nDate: 10-10-2026 12:43 IST\n'

In [121]:
!pip install itables -q

In [122]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
from itables import show

In [123]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-02\data\lev-02_merged.parquet"
pdf = pl.scan_parquet(path)

In [124]:
pdf.collect_schema()

Schema([('Survey_Name', String),
        ('Year', String),
        ('FSU_Serial_No', String),
        ('Sector', String),
        ('State', String),
        ('NSS_Region', String),
        ('District', String),
        ('Stratum', String),
        ('Sub_stratum', String),
        ('Panel', String),
        ('Sub_sample', String),
        ('FOD_Sub_Region', String),
        ('Sample_SU_No', String),
        ('Sample_Sub_Division_No', String),
        ('Second_Stage_Stratum_No', String),
        ('Sample_Household_No', String),
        ('Questionnaire_No', String),
        ('Level', String),
        ('Person_Serial_No', String),
        ('Relation_to_Head', String),
        ('Gender', String),
        ('Age', String),
        ('Marital_Status', String),
        ('Education_Level', String),
        ('Years_of_Education', String),
        ('Used_Internet_Last_30_Days', String),
        ('Days_Away_From_Home_Last_30_Days', String),
        ('Meals_Usually_Taken_Per_Day', String),
        ('Meals_From_School', String),
        ('Meals_From_Employer', String),
        ('Meals_Other', String),
        ('Meals_On_Payment', String),
        ('Meals_At_Home', String),
        ('Revisit_Status', String),
        ('FDQ_Original_Member', String),
        ('Multiplier', Int64)])

# Useful Variables

In [125]:
lev_02_hh = [ 'Revisit_Status', 'FDQ_Original_Member', 'Multiplier']

lev_02_food = ['Meals_Usually_Taken_Per_Day','Meals_From_School',
               'Meals_From_Employer','Meals_Other',
               'Meals_On_Payment','Meals_At_Home']

lev_02_digital = ['Used_Internet_Last_30_Days']

lev_02__behavior = ['Days_Away_From_Home_Last_30_Days']

lev_02_user = ['FSU_Serial_No', 'Relation_to_Head','Gender',
               'Age', 'Marital_Status', 
               'Education_Level', 'Years_of_Education']

In [126]:
lev_02_cols = (
    lev_02_hh
    + lev_02_food
    + lev_02_digital
    + lev_02__behavior
    + lev_02_user
)

In [127]:
df = pdf.select(lev_02_cols)

In [128]:
df

In [129]:
df.head(2).collect()

shape: (2, 18)
┌────────────┬────────────┬────────────┬────────────┬───┬─────┬────────────┬───────────┬───────────┐
│ Revisit_St ┆ FDQ_Origin ┆ Multiplier ┆ Meals_Usua ┆ … ┆ Age ┆ Marital_St ┆ Education ┆ Years_of_ │
│ atus       ┆ al_Member  ┆ ---        ┆ lly_Taken_ ┆   ┆ --- ┆ atus       ┆ _Level    ┆ Education │
│ ---        ┆ ---        ┆ i64        ┆ Per_Day    ┆   ┆ str ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ str        ┆            ┆ ---        ┆   ┆     ┆ str        ┆ str       ┆ str       │
│            ┆            ┆            ┆ str        ┆   ┆     ┆            ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═════╪════════════╪═══════════╪═══════════╡
│ 1          ┆ 1          ┆ 153083     ┆ 3          ┆ … ┆ 58  ┆ 2          ┆ 12        ┆ 15        │
│ 1          ┆ 1          ┆ 153083     ┆ 3          ┆ … ┆ 47  ┆ 2          ┆ 05        ┆ 9         │
└────────────┴────────────┴────────────┴────────────┴───┴─────┴────────────┴───────────┴───────────┘

In [130]:
df = df.with_columns(
    [pl.col(col).cast(pl.Int32, strict=False) for col in lev_02_cols]
)

In [131]:
unique_counts = df.select(pl.all().n_unique()).collect()
unique_counts

shape: (1, 18)
┌────────────┬────────────┬────────────┬────────────┬───┬─────┬────────────┬───────────┬───────────┐
│ Revisit_St ┆ FDQ_Origin ┆ Multiplier ┆ Meals_Usua ┆ … ┆ Age ┆ Marital_St ┆ Education ┆ Years_of_ │
│ atus       ┆ al_Member  ┆ ---        ┆ lly_Taken_ ┆   ┆ --- ┆ atus       ┆ _Level    ┆ Education │
│ ---        ┆ ---        ┆ u32        ┆ Per_Day    ┆   ┆ u32 ┆ ---        ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆            ┆ ---        ┆   ┆     ┆ u32        ┆ u32       ┆ u32       │
│            ┆            ┆            ┆ u32        ┆   ┆     ┆            ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═════╪════════════╪═══════════╪═══════════╡
│ 3          ┆ 2          ┆ 23567      ┆ 5          ┆ … ┆ 112 ┆ 4          ┆ 12        ┆ 23        │
└────────────┴────────────┴────────────┴────────────┴───┴─────┴────────────┴───────────┴───────────┘

In [132]:
unique_counts = df.select(pl.all().n_unique()).collect()

categorical_cols = []
numerical_cols = []

for col in df.columns:
    if unique_counts[col][0] <13:
        categorical_cols.append(col)
    else:
        numerical_cols.append(col)

C:\Users\Rudra\AppData\Local\Temp\ipykernel_9736\3703037397.py:6: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  for col in df.columns:

In [137]:
stats = df.select(numerical_cols).describe()
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    display(stats.to_pandas().T)

,0,1,2,3,4,5,6,7,8
statistic,count,null_count,mean,std,min,25%,50%,75%,max
Multiplier,1107221.0,0.0,110204.903746,74405.615919,369.0,57399.0,113880.0,149314.0,2366902.0
Meals_From_School,349498.0,757723.0,3.634107,7.643276,0.0,0.0,0.0,0.0,26.0
Meals_From_Employer,302727.0,804494.0,0.416748,3.967427,0.0,0.0,0.0,0.0,90.0
Meals_Other,397376.0,709845.0,1.95688,6.117316,0.0,0.0,0.0,2.0,90.0
Meals_On_Payment,374187.0,733034.0,1.99213,8.397705,0.0,0.0,0.0,1.0,98.0
Meals_At_Home,1099541.0,7680.0,74.35818,16.485763,-5.0,60.0,80.0,90.0,95.0
Days_Away_From_Home_Last_30_Days,1105059.0,2162.0,0.205287,1.317463,0.0,0.0,0.0,0.0,30.0
FSU_Serial_No,1107221.0,0.0,38108.869331,9703.436333,22300.0,27037.0,42797.0,46379.0,49999.0
Age,1107221.0,0.0,31.547072,19.750673,0.0,15.0,29.0,45.0,120.0
Years_of_Education,844761.0,262460.0,9.690214,4.457335,0.0,6.0,10.0,13.0,21.0

In [138]:
for col in categorical_cols:
    print(col)
    counts = df.select(pl.col(col).value_counts(sort=True)).collect()
    
    with pl.Config(tbl_rows=-1, tbl_cols=-1):
        display(counts.unnest(col))

Revisit_Status

shape: (3, 2)
┌────────────────┬─────────┐
│ Revisit_Status ┆ count   │
│ ---            ┆ ---     │
│ i32            ┆ u32     │
╞════════════════╪═════════╡
│ 1              ┆ 1103470 │
│ 2              ┆ 1955    │
│ 3              ┆ 1796    │
└────────────────┴─────────┘

FDQ_Original_Member

shape: (2, 2)
┌─────────────────────┬─────────┐
│ FDQ_Original_Member ┆ count   │
│ ---                 ┆ ---     │
│ i32                 ┆ u32     │
╞═════════════════════╪═════════╡
│ 1                   ┆ 1105059 │
│ null                ┆ 2162    │
└─────────────────────┴─────────┘

Meals_Usually_Taken_Per_Day

shape: (5, 2)
┌─────────────────────────────┬────────┐
│ Meals_Usually_Taken_Per_Day ┆ count  │
│ ---                         ┆ ---    │
│ i32                         ┆ u32    │
╞═════════════════════════════╪════════╡
│ 3                           ┆ 635930 │
│ 2                           ┆ 458695 │
│ 0                           ┆ 8672   │
│ null                        ┆ 2600   │
│ 1                           ┆ 1324   │
└─────────────────────────────┴────────┘

Used_Internet_Last_30_Days

shape: (3, 2)
┌────────────────────────────┬────────┐
│ Used_Internet_Last_30_Days ┆ count  │
│ ---                        ┆ ---    │
│ i32                        ┆ u32    │
╞════════════════════════════╪════════╡
│ 1                          ┆ 625632 │
│ 2                          ┆ 442901 │
│ null                       ┆ 38688  │
└────────────────────────────┴────────┘

Relation_to_Head

shape: (9, 2)
┌──────────────────┬────────┐
│ Relation_to_Head ┆ count  │
│ ---              ┆ ---    │
│ i32              ┆ u32    │
╞══════════════════╪════════╡
│ 5                ┆ 356483 │
│ 1                ┆ 261953 │
│ 2                ┆ 200309 │
│ 6                ┆ 96840  │
│ 3                ┆ 65033  │
│ 4                ┆ 63573  │
│ 7                ┆ 31329  │
│ 8                ┆ 29904  │
│ 9                ┆ 1797   │
└──────────────────┴────────┘

Gender

shape: (3, 2)
┌────────┬────────┐
│ Gender ┆ count  │
│ ---    ┆ ---    │
│ i32    ┆ u32    │
╞════════╪════════╡
│ 1      ┆ 564256 │
│ 2      ┆ 542751 │
│ 3      ┆ 214    │
└────────┴────────┘

Marital_Status

shape: (4, 2)
┌────────────────┬────────┐
│ Marital_Status ┆ count  │
│ ---            ┆ ---    │
│ i32            ┆ u32    │
╞════════════════╪════════╡
│ 2              ┆ 557180 │
│ 1              ┆ 483369 │
│ 3              ┆ 62062  │
│ 4              ┆ 4610   │
└────────────────┴────────┘

Education_Level

shape: (12, 2)
┌─────────────────┬────────┐
│ Education_Level ┆ count  │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ 1               ┆ 240429 │
│ 4               ┆ 149644 │
│ 5               ┆ 148063 │
│ 6               ┆ 140876 │
│ 3               ┆ 136151 │
│ 7               ┆ 123447 │
│ 12              ┆ 104231 │
│ 13              ┆ 26686  │
│ 2               ┆ 22031  │
│ 10              ┆ 8038   │
│ 11              ┆ 4746   │
│ 8               ┆ 2879   │
└─────────────────┴────────┘