In [39]:
!pip install findmyjoint

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: findmyjoint in c:\users\rudra\appdata\roaming\python\python311\site-packages (0.0.1)
Requirement already satisfied: pandas>=1.3 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from findmyjoint) (2.2.3)
Requirement already satisfied: pyvis>=0.3 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from findmyjoint) (0.3.2)
Requirement already satisfied: rapidfuzz>=2.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from findmyjoint) (3.14.1)
Requirement already satisfied: numpy>=1.23.2 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.3->findmyjoint) (1.17.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (9.3.0)
Requirement already satisfied: jinja2>=2.9.6 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (3.1.6)
Requirement already satisfied: jsonpickle>=1.4.1 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (4.1.1)
Requirement already satisfied: networkx>=1.11 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (3.5)
Requirement already satisfied: colorama in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.4.6)
Requirement already satisfied: decorator in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (2.19.2)
Requirement already satisfied: stack_data in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (4.14.0)
Requirement already satisfied: wcwidth in c:\users\rudra\appdata\roaming\python\python311\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from jedi>=0.16->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from jinja2>=2.9.6->pyvis>=0.3->findmyjoint) (3.0.2)
Requirement already satisfied: executing>=1.2.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from stack_data->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from stack_data->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\rudra\appdata\roaming\python\python311\site-packages (from stack_data->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.2.3)

In [40]:
import os
import pandas as pd 
import findmyjoint as fmj

- This python library created by me
- This help us to find the joint for dataset
- Repo: https://github.com/Rudra-G-23/Find-My-Joint
- Documentation : https://rudra-g-23.github.io/Find-My-Joint/

In [41]:
def load_dataset(path, df_name):
    df_name = pd.read_csv(path)
    return df_name

In [42]:
ROOT_DIR = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\sample-csv"

In [43]:
datasets = []

for i in range (1, 16):
    
    level = f"{i:02d}"
    name = f"df_{i:02d}"
    
    path = os.path.join(ROOT_DIR, f"sample-lev-{level}.csv")
    name = load_dataset(path=path, df_name=name)
    
    datasets.append(name)

In [44]:
datasets

[    Survey_Name  Year  FSU_Serial_No  Sector  State  NSS_Region  District  \
 0          HCES  2024          46667       1      1          12         6
 1          HCES  2024          46667       1      1          12         6
 2          HCES  2024          46667       1      1          12         6
 3          HCES  2024          46667       1      1          12         6
 4          HCES  2024          46667       1      1          12         6
 ..          ...   ...            ...     ...    ...         ...       ...
 995        HCES  2024          46642       1      1          12        17
 996        HCES  2024          46642       1      1          12        17
 997        HCES  2024          46642       1      1          12        17
 998        HCES  2024          46642       1      1          12        17
 999        HCES  2024          46642       1      1          12        17

      Stratum  Sub_stratum  Panel  ...  FOD_Sub_Region  Sample_SU_No  \
 0         13            1      2  ...             110             3
 1         13            1      2  ...             110             3
 2         13            1      2  ...             110             3
 3         13            1      2  ...             110             3
 4         13            1      2  ...             110             3
 ..       ...          ...    ...  ...             ...           ...
 995       23            4      2  ...             111             9
 996       23            4      2  ...             111             9
 997       23            4      2  ...             111             9
 998       23            4      2  ...             111             9
 999       23            4      2  ...             111             9

      Sample_Sub_Division_No  Second_Stage_Stratum_No  Sample_Household_No  \
 0                       NaN                        2                    1
 1                       NaN                        3                    1
 2                       NaN                        3                    2
 3                       NaN                        3                    3
 4                       NaN                        3                    4
 ..                      ...                      ...                  ...
 995                     NaN                        3                    5
 996                     NaN                        3                    6
 997                     NaN                        3                    7
 998                     NaN                        3                    8
 999                     NaN                        3                    9

      Questionnaire_No Level  Survey_Code  Reason_for_Substitution_Code  \
 0                   H     1            1                           NaN
 1                   H     1            1                           NaN
 2                   H     1            1                           NaN
 3                   H     1            1                           NaN
 4                   H     1            1                           NaN
 ..                ...   ...          ...                           ...
 995                 H     1            1                           NaN
 996                 H     1            1                           NaN
 997                 H     1            1                           NaN
 998                 H     1            1                           NaN
 999                 H     1            1                           NaN

      Multiplier
 0       16669.0
 1       24840.0
 2       24840.0
 3       24840.0
 4       24840.0
 ..          ...
 995     82854.0
 996     82854.0
 997     82854.0
 998     82854.0
 999     82854.0

 [1000 rows x 21 columns],
     Survey_Name  Year  FSU_Serial_No  Sector  State  NSS_Region  District  \
 0          HCES  2024          40376       1     32         321         5
 1          HCES  2024          40376       1     32         321         5
 2          HCES  2024          40376       1     32         321         5
 3          HCES  2024          40376       1     32         321         5
 4          HCES  2024          40376       1     32         321         5
 ..          ...   ...            ...     ...    ...         ...       ...
 995        HCES  2024          46608       1      1          13        15
 996        HCES  2024          46608       1      1          13        15
 997        HCES  2024          46608       1      1          13        15
 998        HCES  2024          46608       1      1          13        15
 999        HCES  2024          46608       1      1          13        15

      Stratum  Sub_stratum  Panel  ...  Days_Away_From_Home_Last_30_Days  \
 0         23            2      1  ...                                 0
 1         23            2      1  ...                                 0
 2         23            2      1  ...                                 0
 3         23            2      1  ...                                 0
 4         23            2      1  ...                                 0
 ..       ...          ...    ...  ...                               ...
 995       23            4     10  ...                                 0
 996       23            4     10  ...                                 0
 997       23            4     10  ...                                 0
 998       23            4     10  ...                                 0
 999       23            4     10  ...                                 0

      Meals_Usually_Taken_Per_Day  Meals_From_School  Meals_From_Employer  \
 0                              3                NaN                  NaN
 1                              3                NaN                  NaN
 2                              3                NaN                  NaN
 3                              3                NaN                  NaN
 4                              3                NaN                  NaN
 ..                           ...                ...                  ...
 995                            2               15.0                  NaN
 996                            2               16.0                  NaN
 997                            2                NaN                 25.0
 998                            2                NaN                  NaN
 999                            2                NaN                 20.0

      Meals_Other  Meals_On_Payment Meals_At_Home  Revisit_Status  \
 0            3.0               NaN            87               1
 1            2.0               NaN            88               1
 2            2.0               NaN            88               1
 3            NaN               NaN            90               1
 4            6.0               NaN            84               1
 ..           ...               ...           ...             ...
 995          NaN               NaN            45               1
 996          NaN               NaN            44               1
 997          NaN               NaN            35               1
 998          NaN               NaN            60               1
 999          NaN               NaN            40               1

      FDQ_Original_Member  Multiplier
 0                      1      153083
 1                      1      153083
 2                      1      153083
 3                      1      153083
 4                      1      153083
 ..                   ...         ...
 995                    1      165619
 996                    1      165619
 997                    1      165619
 998                    1      165619
 999                    1      165619

 [1000 rows x 36 columns],
     Survey_Name  Year  FSU_Serial_No  Sector  State  NSS_Region  District  \
 0          HCES  2024          46667       1      1          12         6
 1          HCES  2024          46667       1      1          12         6
 2          HCES  2024          46667       1      1          12         6
 3          HCES  2024          46667       1      1          12         6
 4          HCES  2024          46667       1      1          12         6
 ..          ...   ...            ...     ...    ...         ...       ...
 995        HCES  2024          46642       1      1          12        17
 996        HCES  2024          46642       1      1          12        17
 997        HCES  2024          46642       1      1          12        17
 998        HCES  2024          46642       1      1          12        17
 999        HCES  2024          46642       1      1          12        17

      Stratum  Sub_stratum  Panel  ...  Type_of_Land_Owned  \
 0         13            1      2  ...                 2.0
 1         13            1      2  ...                 2.0
 2         13            1      2  ...                 2.0
 3         13            1      2  ...                 2.0
 4         13            1      2  ...                 2.0
 ..       ...          ...    ...  ...                 ...
 995       23            4      2  ...                 2.0
 996       23            4      2  ...                 2.0
 997       23            4      2  ...                 2.0
 998       23            4      2  ...                 2.0
 999       23            4      2  ...                 2.0

      Total_Area_Land_Owned_Acres  Dwelling_Unit_Exists  Type_of_Dwelling_Unit  \
 0                           1.87                     1                    1.0
 1                           0.51                     1                    1.0
 2                           0.52                     1                    1.0
 3                           0.03                     1                    1.0
 4                           0.51                     1                    1.0
 ..                           ...                   ...                    ...
 995                         0.62                     1                    1.0
 996                         0.37                     1                    1.0
 997                         0.37                     1                    1.0
 998                         0.25                     1                    1.0
 999                         0.37                     1                    1.0

      Energy_Source_Cooking  Energy_Source_Lighting Ration_Card_Type  \
 0                        2                       1                3
 1                        2                       1                3
 2                        2                       1                2
 3                        2                       1                3
 4                        2                       1                3
 ..                     ...                     ...              ...
 995                      1                       1                4
 996                      1                       1                3
 997                      1                       1                2
 998                      1                       1                2
 999                      1                       1                2

      Rent_Rate_Available_Rural  Benefitted_From_PMGKY  Multiplier
 0                            2                      2     16669.0
 1                            2                      2     24840.0
 2                            2                      1     24840.0
 3                            2                      1     24840.0
 4                            2                      1     24840.0
 ..                         ...                    ...         ...
 995                          2                      1     82854.0
 996                          2                      2     82854.0
 997                          2                      1     82854.0
 998                          2                      1     82854.0
 999                          2                      1     82854.0

 [1000 rows x 40 columns],
     Survey_Name  Year  FSU_Serial_No  Sector  State  NSS_Region  District  \
 0          HCES  2024          46661       1      1          11        21
 1          HCES  2024          46661       1      1          11        21
 2          HCES  2024          46661       1      1          11        21
 3          HCES  2024          46661       1      1          11        21
 4          HCES  2024          46661       1      1          11        21
 ..          ...   ...            ...     ...    ...         ...       ...
 995        HCES  2024          46270       1      6          61         8
 996        HCES  2024          46270       1      6          61         8
 997        HCES  2024          46270       1      6          61         8
 998        HCES  2024          46270       1      6          61         8
 999        HCES  2024          46270       1      6          61         8

      Stratum  Sub_stratum  Panel  ...  Online_Vegetables  Online_Fresh_Fruits  \
 0         22            1      1  ...                NaN                  NaN
 1         22            1      1  ...                NaN                  NaN
 2         22            1      1  ...                NaN                  NaN
 3         22            1      1  ...                NaN                  NaN
 4         22            1      1  ...                NaN                  NaN
 ..       ...          ...    ...  ...                ...                  ...
 995       23            4      1  ...                NaN                  NaN
 996       23            4      1  ...                NaN                  NaN
 997       23            4      1  ...                NaN                  NaN
 998       23            4      1  ...                NaN                  NaN
 999       23            4      1  ...                NaN                  NaN

      Online_Dry_Fruits  Online_Egg_Fish_Meat  Online_Served_Processed_Food  \
 0                  NaN                   NaN                           NaN
 1                  NaN                   NaN                           NaN
 2                  NaN                   NaN                           NaN
 3                  NaN                   NaN                           NaN
 4                  NaN                   NaN                           NaN
 ..                 ...                   ...                           ...
 995                NaN                   NaN                           NaN
 996                NaN                   NaN                           NaN
 997                NaN                   NaN                           NaN
 998                NaN                   NaN                           NaN
 999                NaN                   NaN                           NaN

      Online_Packed_Processed_Food Online_Other_Food_Items  \
 0                             NaN                     NaN
 1                             NaN                     NaN
 2                             NaN                     NaN
 3                             NaN                     NaN
 4                             NaN                     NaN
 ..                            ...                     ...
 995                           NaN                     NaN
 996                           NaN                     NaN
 997                           NaN                     NaN
 998                           NaN                     NaN
 999                           NaN                     NaN

      Ceremony_Performed_Last_30_Days  Meals_Served_to_Non_HH_Members  \
 0                                  2                               5
 1                                  2                               5
 2                                  2                               5
 3                                  2                               8
 4                                  2                               8
 ..                               ...                             ...
 995                                2                               5
 996                                2                               5
 997                                2                               0
 998                                2                               0
 999                                2                               8

      Multiplier
 0      192686.0
 1      177967.0
 2      177967.0
 3      177967.0
 4      117217.0
 ..          ...
 995    143841.0
 996    143841.0
 997    143841.0
 998    143841.0
 999    143841.0

 [1000 rows x 38 columns],
     Survey_Name  Year  FSU_Serial_No  Sector  State  NSS_Region  District  \
 0          HCES  2024          46667       1      1          12         6
 1          HCES  2024          46667       1      1          12         6
 2          HCES  2024          46667       1      1          12         6
 3          HCES  2024          46667       1      1          12         6
 4          HCES  2024          46667       1      1          12         6
 ..          ...   ...            ...     ...    ...         ...       ...
 995        HCES  2024          46663       1      1          12         6
 996        HCES  2024          46663       1      1          12         6
 997        HCES  2024          46663       1      1          12         6
 998        HCES  2024          46663       1      1          12         6
 999        HCES  2024          46663       1      1          12         6

      Stratum  Sub_stratum  Panel  ...  Sample_Household_No  Questionnaire_No  \
 0         13            1      2  ...                    1                 F
 1         13            1      2  ...                    1                 F
 2         13            1      2  ...                    1                 F
 3         13            1      2  ...                    1                 F
 4         13            1      2  ...                    1                 F
 ..       ...          ...    ...  ...                  ...               ...
 995       13            1      3  ...                   12                 F
 996       13            1      3  ...                   12                 F
 997       13            1      3  ...                   12                 F
 998       13            1      3  ...                   12                 F
 999       13            1      3  ...                   12                 F

      Level  Item_Code  OutOfHome_Consumption_Quantity  \
 0        5          2                            10.0
 1        5          3                             NaN
 2        5        101                             NaN
 3        5        107                             NaN
 4        5        108                             NaN
 ..     ...        ...                             ...
 995      5        173                             NaN
 996      5        181                             NaN
 997      5        184                             NaN
 998      5        190                             NaN
 999      5        195                             NaN

      OutOfHome_Consumption_Value Total_Consumption_Quantity  \
 0                          250.0                      10.00
 1                            NaN                       0.50
 2                            NaN                      15.00
 3                            NaN                      10.00
 4                            NaN                       5.00
 ..                           ...                        ...
 995                          NaN                       0.50
 996                          NaN                       1.10
 997                          NaN                       0.25
 998                          NaN                       5.00
 999                          NaN                       2.00

      Total_Consumption_Value  Source  Multiplier
 0                      250.0     2.0       16669
 1                      160.0     1.0       16669
 2                      225.0     1.0       16669
 3                      130.0     1.0       16669

In [45]:
print("--- Comparison Matrix ---")
matrix = fmj.compare(datasets)
print(matrix.head())

--- Comparison Matrix ---
  dataset_left  column_left dataset_right column_right  name_sim  dtype_match  \
0          ds0         Year           ds4         Year       1.0          1.0
1          ds0  Survey_Name           ds2  Survey_Name       1.0          1.0
2          ds8  Sub_stratum          ds14  Sub_stratum       1.0          1.0
3          ds8   Sub_sample          ds10   Sub_sample       1.0          1.0
4          ds8   Sub_sample           ds9   Sub_sample       1.0          1.0

   content_sim  suggestion  edge_weight
0          1.0  Merge-safe          1.0
1          1.0  Merge-safe          1.0
2          1.0  Merge-safe          1.0
3          1.0  Merge-safe          1.0
4          1.0  Merge-safe          1.0

In [51]:
matrix.to_csv("matrix.csv")

In [50]:
matrix

,dataset_left,column_left,dataset_right,column_right,name_sim,dtype_match,content_sim,suggestion,edge_weight
0,ds0,Year,ds4,Year,1.000000,1.0,1.0,Merge-safe,1.000000
1,ds0,Survey_Name,ds2,Survey_Name,1.000000,1.0,1.0,Merge-safe,1.000000
2,ds8,Sub_stratum,ds14,Sub_stratum,1.000000,1.0,1.0,Merge-safe,1.000000
3,ds8,Sub_sample,ds10,Sub_sample,1.000000,1.0,1.0,Merge-safe,1.000000
4,ds8,Sub_sample,ds9,Sub_sample,1.000000,1.0,1.0,Merge-safe,1.000000
...,...,...,...,...,...,...,...,...,...
13339,ds4,Survey_Name,ds12,Sub_sample,0.571429,0.0,0.0,Review,0.228571
13340,ds0,Survey_Name,ds5,Sub_sample,0.571429,0.0,0.0,Review,0.228571
13341,ds4,Survey_Name,ds6,Sub_sample,0.571429,0.0,0.0,Review,0.228571
13342,ds12,Sub_sample,ds14,Survey_Name,0.571429,0.0,0.0,Review,0.228571
13343,ds1,Years_of_Education,ds14,SECTION,0.560000,0.0,0.0,Review,0.224000

In [49]:
matrix[matrix['suggestion'] == 'Merge-safe']

,dataset_left,column_left,dataset_right,column_right,name_sim,dtype_match,content_sim,suggestion,edge_weight
0,ds0,Year,ds4,Year,1.0,1.0,1.0,Merge-safe,1.00
1,ds0,Survey_Name,ds2,Survey_Name,1.0,1.0,1.0,Merge-safe,1.00
2,ds8,Sub_stratum,ds14,Sub_stratum,1.0,1.0,1.0,Merge-safe,1.00
3,ds8,Sub_sample,ds10,Sub_sample,1.0,1.0,1.0,Merge-safe,1.00
4,ds8,Sub_sample,ds9,Sub_sample,1.0,1.0,1.0,Merge-safe,1.00
...,...,...,...,...,...,...,...,...,...
698,ds0,Panel,ds14,Panel,1.0,1.0,0.9,Merge-safe,0.96
699,ds10,Panel,ds14,Panel,1.0,1.0,0.9,Merge-safe,0.96
700,ds13,Panel,ds14,Panel,1.0,1.0,0.9,Merge-safe,0.96
701,ds9,Panel,ds14,Panel,1.0,1.0,0.9,Merge-safe,0.96
702,ds2,Panel,ds7,Panel,1.0,1.0,0.9,Merge-safe,0.96

In [46]:
print("\n--- Generating Network Graph ---")
fmj.network(datasets)
print("Graph 'joint_graph.html' created.")

--- Generating Network Graph ---
No matches found. Running match_columns() first...
Building graph with connections stronger than 0.5...
Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
joint_graph.html
Success! Interactive graph saved to: c:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\notebooks\merging-dataset\joint_graph.html
Opening in your default browser...
Graph 'joint_graph.html' created.

Youtube Video: https://youtu.be/TlMWL8CpebY