In [39]:
!pip install findmyjoint

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: findmyjoint in c:\users\rudra\appdata\roaming\python\python311\site-packages (0.0.1)
Requirement already satisfied: pandas>=1.3 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from findmyjoint) (2.2.3)
Requirement already satisfied: pyvis>=0.3 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from findmyjoint) (0.3.2)
Requirement already satisfied: rapidfuzz>=2.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from findmyjoint) (3.14.1)
Requirement already satisfied: numpy>=1.23.2 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pandas>=1.3->findmyjoint) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.3->findmyjoint) (1.17.0)
Requirement already satisfied: ipython>=5.3.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (9.3.0)
Requirement already satisfied: jinja2>=2.9.6 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (3.1.6)
Requirement already satisfied: jsonpickle>=1.4.1 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (4.1.1)
Requirement already satisfied: networkx>=1.11 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from pyvis>=0.3->findmyjoint) (3.5)
Requirement already satisfied: colorama in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.4.6)
Requirement already satisfied: decorator in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (2.19.2)
Requirement already satisfied: stack_data in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from ipython>=5.3.0->pyvis>=0.3->findmyjoint) (4.14.0)
Requirement already satisfied: wcwidth in c:\users\rudra\appdata\roaming\python\python311\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from jedi>=0.16->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from jinja2>=2.9.6->pyvis>=0.3->findmyjoint) (3.0.2)
Requirement already satisfied: executing>=1.2.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from stack_data->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\rudra\appdata\roaming\python\python311\site-packages (from stack_data->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\rudra\appdata\roaming\python\python311\site-packages (from stack_data->ipython>=5.3.0->pyvis>=0.3->findmyjoint) (0.2.3)

In [40]:
import os
import pandas as pd 
import findmyjoint as fmj

- This python library created by me
- This help us to find the joint for dataset
- Repo: https://github.com/Rudra-G-23/Find-My-Joint
- Documentation : https://rudra-g-23.github.io/Find-My-Joint/

In [4]:
df1 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\sample-csv\sample-lev-01.csv")
df2 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\sample-csv\sample-lev-02.csv")

In [5]:
datasets = [df1, df2]

In [6]:
print("--- Comparison Matrix ---")
matrix = fmj.compare(datasets)
print(matrix.head())

--- Comparison Matrix ---
  dataset_left          column_left dataset_right         column_right  \
0          ds0          Survey_Name           ds1          Survey_Name
1          ds0                 Year           ds1                 Year
2          ds0          Sub_stratum           ds1          Sub_stratum
3          ds0              Stratum           ds1              Stratum
4          ds0  Sample_Household_No           ds1  Sample_Household_No

   name_sim  dtype_match  content_sim  suggestion  edge_weight
0       1.0          1.0          1.0  Merge-safe          1.0
1       1.0          1.0          1.0  Merge-safe          1.0
2       1.0          1.0          1.0  Merge-safe          1.0
3       1.0          1.0          1.0  Merge-safe          1.0
4       1.0          1.0          1.0  Merge-safe          1.0

In [7]:
matrix

,dataset_left,column_left,dataset_right,column_right,name_sim,dtype_match,content_sim,suggestion,edge_weight
0,ds0,Survey_Name,ds1,Survey_Name,1.000000,1.0,1.0,Merge-safe,1.000000
1,ds0,Year,ds1,Year,1.000000,1.0,1.0,Merge-safe,1.000000
2,ds0,Sub_stratum,ds1,Sub_stratum,1.000000,1.0,1.0,Merge-safe,1.000000
3,ds0,Stratum,ds1,Stratum,1.000000,1.0,1.0,Merge-safe,1.000000
4,ds0,Sample_Household_No,ds1,Sample_Household_No,1.000000,1.0,1.0,Merge-safe,1.000000
...,...,...,...,...,...,...,...,...,...
115,ds0,Panel,ds1,Sub_stratum,0.125000,1.0,0.4,Review,0.410000
116,ds0,Sub_stratum,ds1,Panel,0.125000,1.0,0.4,Review,0.410000
117,ds0,Survey_Code,ds1,Survey_Name,0.727273,0.0,0.0,Review,0.290909
118,ds0,Sub_sample,ds1,Survey_Name,0.571429,0.0,0.0,Review,0.228571
119,ds0,Survey_Name,ds1,Sub_sample,0.571429,0.0,0.0,Review,0.228571

In [8]:
matrix[matrix['suggestion'] == 'Merge-safe']

,dataset_left,column_left,dataset_right,column_right,name_sim,dtype_match,content_sim,suggestion,edge_weight
0,ds0,Survey_Name,ds1,Survey_Name,1.0,1.0,1.0,Merge-safe,1.0
1,ds0,Year,ds1,Year,1.0,1.0,1.0,Merge-safe,1.0
2,ds0,Sub_stratum,ds1,Sub_stratum,1.0,1.0,1.0,Merge-safe,1.0
3,ds0,Stratum,ds1,Stratum,1.0,1.0,1.0,Merge-safe,1.0
4,ds0,Sample_Household_No,ds1,Sample_Household_No,1.0,1.0,1.0,Merge-safe,1.0
5,ds0,Questionnaire_No,ds1,Questionnaire_No,1.0,1.0,1.0,Merge-safe,1.0
6,ds0,Second_Stage_Stratum_No,ds1,Second_Stage_Stratum_No,1.0,1.0,1.0,Merge-safe,1.0
7,ds0,Sub_sample,ds1,Sub_sample,1.0,1.0,1.0,Merge-safe,1.0

In [ ]:
print("\n--- Generating Network Graph ---")
fmj.network(datasets, out="joint_graph2.html")
print("Graph 'joint_graph.html' created.")

--- Generating Network Graph ---
No matches found. Running match_columns() first...
Building graph with connections stronger than 0.5...
Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
joint_graph.html
Success! Interactive graph saved to: c:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\notebooks\merging-dataset\joint_graph.html
Opening in your default browser...

Graph 'joint_graph.html' created.