In [3]:
import pandas as pd

In [4]:
df5 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\bihar-datasets\BL05.csv")
df9 = pd.read_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\bihar-datasets\BL09.csv")

In [5]:
df5.shape

(841515, 29)

In [6]:
df9.shape

(542787, 25)

In [80]:
df5.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'Item_Code', 'OutOfHome_Consumption_Quantity',
       'OutOfHome_Consumption_Value', 'Total_Consumption_Quantity',
       'Total_Consumption_Value', 'Source', 'Multiplier', 'Sector_label',
       'State_label', 'ingest_timestamp', 'ingest_date'],
      dtype='object')

In [81]:
df9.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'Item_Code_9_1_to_11_4', 'Value_Rs_9_1_to_11_4', 'Multiplier',
       'Sector_label', 'State_label', 'ingest_timestamp', 'ingest_date'],
      dtype='object')

In [82]:
'8' + '9'

'89'

In [83]:
combine_cols = ['FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No',]

In [84]:
df5[combine_cols].notnull().sum()

FSU_Serial_No              841515
Sector                     841515
State                      841515
NSS_Region                 841515
District                   841515
Stratum                    841515
Sub_stratum                841515
Panel                      841515
Sub_sample                 841515
FOD_Sub_Region             841515
Sample_SU_No               841515
Sample_Sub_Division_No       2046
Second_Stage_Stratum_No    841515
Sample_Household_No        841515
dtype: int64

In [85]:
df9[combine_cols].notnull().sum()

FSU_Serial_No              542787
Sector                     542787
State                      542787
NSS_Region                 542787
District                   542787
Stratum                    542787
Sub_stratum                542787
Panel                      542787
Sub_sample                 542787
FOD_Sub_Region             542787
Sample_SU_No               542787
Sample_Sub_Division_No       1263
Second_Stage_Stratum_No    542787
Sample_Household_No        542787
dtype: int64

In [86]:
df5['Sample_Sub_Division_No'].unique()

array([nan,  2.,  1.])

In [103]:
df5['Item_Code'].unique()

array([141, 143, 144, 146, 150, 152, 160, 163, 170, 172, 173, 174, 181,
       184, 191, 195, 200, 201, 202, 203, 204, 205, 206, 207, 211, 212,
       214, 215, 216, 217, 220, 230, 237, 241, 242, 246, 250, 251, 252,
       253, 254, 255, 256, 258, 260, 270, 271, 276,   3, 102, 103, 108,
       110, 111, 112, 142, 164, 236, 243, 257,  61,  62,   4, 105, 208,
       210, 213, 231, 261, 140, 192, 222, 275, 235, 245, 278, 190, 232,
       226, 274, 273, 166, 228, 240, 148, 272, 114, 193, 107,  11, 165,
       139, 247, 224, 227,   2, 145, 225,   6, 238, 175, 196, 183,   8,
       122, 223, 106, 101, 233, 194, 221,  10, 162,   7, 185,  95,  93,
        92,  94, 129, 159, 169, 179, 189, 199, 219, 239, 249, 269, 279,
       263, 234, 167,   5, 182, 180])

In [88]:
df9['Item_Code_9_1_to_11_4'].unique()

array([ 17,  20,  21,  22,  23, 400, 404, 405, 420, 422, 450, 451, 452,
       453, 454, 455, 456, 457, 465, 466, 467, 468, 472, 483, 484, 485,
       486, 488, 497, 500, 501, 512, 899, 438, 408, 464, 471, 410, 411,
       412, 413, 414, 520, 496, 504, 421, 490, 430, 406, 492, 521,  18,
       494, 523, 401, 437, 461, 513, 402, 463,  28, 462, 470, 424, 460,
       505, 435, 508, 540,  24,  25,  27, 480, 511, 495, 506, 510, 539,
        16, 514, 482, 522, 487, 433, 423, 493,  26, 481, 479, 409, 429,
       459, 499, 519, 439, 419, 529])

In [89]:
df5[combine_cols].astype(str).agg("".join, axis=1)

0         27865210101141225110101nan315
1         27865210101141225110101nan315
2         27865210101141225110101nan315
3         27865210101141225110101nan315
4         27865210101141225110101nan315
                      ...
841510    27865210101141225110101nan315
841511    27865210101141225110101nan315
841512    27865210101141225110101nan315
841513    27865210101141225110101nan315
841514    27865210101141225110101nan315
Length: 841515, dtype: object

In [90]:
df5[combine_cols].fillna(0).astype(int).astype(str).agg("".join, axis=1) + df5['Item_Code'].astype(str)

0         278652101011412251101010315141
1         278652101011412251101010315143
2         278652101011412251101010315144
3         278652101011412251101010315146
4         278652101011412251101010315150
                       ...
841510    278652101011412251101010315103
841511    278652101011412251101010315108
841512    278652101011412251101010315110
841513    278652101011412251101010315111
841514    278652101011412251101010315112
Length: 841515, dtype: object

In [91]:
df5['item_unique_id'] = df5[combine_cols].fillna(0).astype(int).astype(str).agg("".join, axis=1)  + df5['Item_Code'].astype(str)

In [92]:
df9['item_unique_id'] = df9[combine_cols].fillna(0).astype(int).astype(str).agg("".join, axis=1) + df9['Item_Code_9_1_to_11_4'].astype(str)

# Inner Joint

In [93]:
dfm = df5.merge(df9, on='item_unique_id')

In [94]:
dfm

,Survey_Name_x,Year_x,FSU_Serial_No_x,Sector_x,State_x,NSS_Region_x,District_x,Stratum_x,Sub_stratum_x,Panel_x,...,Sample_Household_No_y,Questionnaire_No_y,Level_y,Item_Code_9_1_to_11_4,Value_Rs_9_1_to_11_4,Multiplier_y,Sector_label_y,State_label_y,ingest_timestamp_y,ingest_date_y
0,HCES,2024,27869,2,10,101,18,12,2,8,...,12,C,9,20,160,37108,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1,HCES,2024,27878,2,10,101,20,12,1,4,...,12,C,9,17,50,38880,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
2,HCES,2024,27870,2,10,101,5,12,1,10,...,12,C,9,17,80,53280,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
3,HCES,2024,27857,2,10,101,5,22,5,6,...,12,C,9,17,40,98859,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
4,HCES,2024,27857,2,10,101,5,22,5,6,...,12,C,9,20,40,98859,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,HCES,2024,27863,2,10,101,14,12,2,3,...,12,C,9,20,150,43632,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1201,HCES,2024,27866,2,10,101,14,12,2,1,...,12,C,9,17,25,48340,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1202,HCES,2024,27865,2,10,101,14,12,2,5,...,12,C,9,17,55,30655,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1203,HCES,2024,27865,2,10,101,14,12,2,5,...,12,C,9,20,120,30655,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1204,HCES,2024,27865,2,10,101,14,12,2,5,...,1,C,9,23,80,30655,urban,Bihar,2026-01-07 05:35:08.025+00,2026-01-07

In [12]:
total = df5.shape[0] + df9.shape[0]
total

1384302

In [11]:
(1205 / total ) * 100

0.0870474795239767

In [96]:
dfm.to_csv("inner-joint-bihar-59.csv")

In [95]:
dfm.columns

Index(['Survey_Name_x', 'Year_x', 'FSU_Serial_No_x', 'Sector_x', 'State_x',
       'NSS_Region_x', 'District_x', 'Stratum_x', 'Sub_stratum_x', 'Panel_x',
       'Sub_sample_x', 'FOD_Sub_Region_x', 'Sample_SU_No_x',
       'Sample_Sub_Division_No_x', 'Second_Stage_Stratum_No_x',
       'Sample_Household_No_x', 'Questionnaire_No_x', 'Level_x', 'Item_Code',
       'OutOfHome_Consumption_Quantity', 'OutOfHome_Consumption_Value',
       'Total_Consumption_Quantity', 'Total_Consumption_Value', 'Source',
       'Multiplier_x', 'Sector_label_x', 'State_label_x', 'ingest_timestamp_x',
       'ingest_date_x', 'item_unique_id', 'Survey_Name_y', 'Year_y',
       'FSU_Serial_No_y', 'Sector_y', 'State_y', 'NSS_Region_y', 'District_y',
       'Stratum_y', 'Sub_stratum_y', 'Panel_y', 'Sub_sample_y',
       'FOD_Sub_Region_y', 'Sample_SU_No_y', 'Sample_Sub_Division_No_y',
       'Second_Stage_Stratum_No_y', 'Sample_Household_No_y',
       'Questionnaire_No_y', 'Level_y', 'Item_Code_9_1_to_11_4',
       'Value_Rs_9_1_to_11_4', 'Multiplier_y', 'Sector_label_y',
       'State_label_y', 'ingest_timestamp_y', 'ingest_date_y'],
      dtype='object')

# Full Joint

In [97]:
dfm = df5.merge(df9, on='item_unique_id', how='outer')

In [98]:
dfm.shape

(1383097, 55)

In [100]:
dfm

,Survey_Name_x,Year_x,FSU_Serial_No_x,Sector_x,State_x,NSS_Region_x,District_x,Stratum_x,Sub_stratum_x,Panel_x,...,Sample_Household_No_y,Questionnaire_No_y,Level_y,Item_Code_9_1_to_11_4,Value_Rs_9_1_to_11_4,Multiplier_y,Sector_label_y,State_label_y,ingest_timestamp_y,ingest_date_y
0,HCES,2024.0,27000.0,2.0,10.0,102.0,37.0,22.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HCES,2024.0,27000.0,2.0,10.0,102.0,37.0,22.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HCES,2024.0,27000.0,2.0,10.0,102.0,37.0,22.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HCES,2024.0,27000.0,2.0,10.0,102.0,37.0,22.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HCES,2024.0,27000.0,2.0,10.0,102.0,37.0,22.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1383092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,C,9.0,500.0,280.0,105400.0,rural,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1383093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,C,9.0,501.0,320.0,105400.0,rural,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1383094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,C,9.0,519.0,2000.0,105400.0,rural,Bihar,2026-01-07 05:35:08.025+00,2026-01-07
1383095,HCES,2024.0,45779.0,1.0,10.0,102.0,34.0,23.0,30.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1383096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,C,9.0,899.0,1100.0,105400.0,rural,Bihar,2026-01-07 05:35:08.025+00,2026-01-07

In [ ]:
dfm.columns

In [101]:
dfm.shape

(1383097, 55)

In [99]:
dfm.to_csv("full-joint-bihar-59.csv")