In [1]:
import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.offline as po

import warnings
warnings.filterwarnings('ignore')

In [2]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-08\data\lev-08_merged.parquet"
pdf = pl.read_parquet(path)

In [3]:
pdf.collect_schema()

Schema([('Survey_Name', String),
        ('Year', String),
        ('FSU_Serial_No', String),
        ('Sector', String),
        ('State', String),
        ('NSS_Region', String),
        ('District', String),
        ('Stratum', String),
        ('Sub_stratum', String),
        ('Panel', String),
        ('Sub_sample', String),
        ('FOD_Sub_Region', String),
        ('Sample_SU_No', String),
        ('Sample_Sub_Division_No', String),
        ('Second_Stage_Stratum_No', String),
        ('Sample_Household_No', String),
        ('Questionnaire_No', String),
        ('Level', String),
        ('Item_Code_8_1', String),
        ('Out_of_home_qty_000', Float64),
        ('Out_of_home_value_rs', Float64),
        ('Total_consumption_qty_000', Float64),
        ('Total_consumption_value_rs', Int64),
        ('Source_8_1', String),
        ('Multiplier', Int64)])

# Where is MP

In [4]:
# Shape of the data
pdf.shape[0]

2999942

In [5]:
pdf['State']

shape: (2_999_942,)
Series: 'State' [str]
[
	"05"
	"05"
	"05"
	"05"
	"05"
	…
	"37"
	"37"
	"37"
	"37"
	"37"
]

In [6]:
# This are label data 
# For know mp we used the Metadata json file
# Line number 308

pdf['State'] == '23'

shape: (2_999_942,)
Series: 'State' [bool]
[
	false
	false
	false
	false
	false
	…
	false
	false
	false
	false
	false
]

In [7]:
mp_data = pdf.filter(
    pl.col('State') == '23'
)

In [8]:
mp_data

shape: (166_502, 25)
┌─────────────┬──────┬────────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Survey_Name ┆ Year ┆ FSU_Serial ┆ Sector ┆ … ┆ Total_cons ┆ Total_cons ┆ Source_8_1 ┆ Multiplier │
│ ---         ┆ ---  ┆ _No        ┆ ---    ┆   ┆ umption_qt ┆ umption_va ┆ ---        ┆ ---        │
│ str         ┆ str  ┆ ---        ┆ str    ┆   ┆ y_000      ┆ lue_rs     ┆ str        ┆ i64        │
│             ┆      ┆ str        ┆        ┆   ┆ ---        ┆ ---        ┆            ┆            │
│             ┆      ┆            ┆        ┆   ┆ f64        ┆ i64        ┆            ┆            │
╞═════════════╪══════╪════════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ HCES        ┆ 2024 ┆ 44085      ┆ 1      ┆ … ┆ 80.0       ┆ 400        ┆ 1          ┆ 58558      │
│ HCES        ┆ 2024 ┆ 44085      ┆ 1      ┆ … ┆ 31.0       ┆ 220        ┆            ┆ 58558      │
│ HCES        ┆ 2024 ┆ 44085      ┆ 1      ┆ … ┆ 30.0       ┆ 60         ┆ 2          ┆ 58558      │
│ HCES        ┆ 2024 ┆ 44085      ┆ 1      ┆ … ┆ 6.0        ┆ 6          ┆ 1          ┆ 58558      │
│ HCES        ┆ 2024 ┆ 44085      ┆ 1      ┆ … ┆ 2.3        ┆ 184        ┆ 1          ┆ 58558      │
│ …           ┆ …    ┆ …          ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ HCES        ┆ 2024 ┆ 25131      ┆ 2      ┆ … ┆ null       ┆ 893        ┆            ┆ 102702     │
│ HCES        ┆ 2024 ┆ 25131      ┆ 2      ┆ … ┆ null       ┆ 1364       ┆            ┆ 102702     │
│ HCES        ┆ 2024 ┆ 25131      ┆ 2      ┆ … ┆ null       ┆ 1041       ┆            ┆ 102702     │
│ HCES        ┆ 2024 ┆ 25131      ┆ 2      ┆ … ┆ null       ┆ 620        ┆            ┆ 102702     │
│ HCES        ┆ 2024 ┆ 25131      ┆ 2      ┆ … ┆ null       ┆ 719        ┆            ┆ 102702     │
└─────────────┴──────┴────────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [9]:
mp_data['FSU_Serial_No'].n_unique()

791

In [10]:
pdf.columns

['Survey_Name',
 'Year',
 'FSU_Serial_No',
 'Sector',
 'State',
 'NSS_Region',
 'District',
 'Stratum',
 'Sub_stratum',
 'Panel',
 'Sub_sample',
 'FOD_Sub_Region',
 'Sample_SU_No',
 'Sample_Sub_Division_No',
 'Second_Stage_Stratum_No',
 'Sample_Household_No',
 'Questionnaire_No',
 'Level',
 'Item_Code_8_1',
 'Out_of_home_qty_000',
 'Out_of_home_value_rs',
 'Total_consumption_qty_000',
 'Total_consumption_value_rs',
 'Source_8_1',
 'Multiplier']

In [11]:
cols = [ 'FSU_Serial_No',
        'Item_Code_8_1',
 'Out_of_home_qty_000',
 'Out_of_home_value_rs',
 'Total_consumption_qty_000',
 'Total_consumption_value_rs',]

In [12]:
idf = pdf[cols]

In [13]:
idf['Item_Code_8_1'].unique().to_list()

['340',
 '331',
 '346',
 '341',
 '349',
 '337',
 '338',
 '332',
 '336',
 '096',
 '343',
 '345',
 '333',
 '335',
 '342',
 '344',
 '334']

In [14]:
idf

shape: (2_999_942, 6)
┌───────────────┬───────────────┬────────────────┬────────────────┬────────────────┬───────────────┐
│ FSU_Serial_No ┆ Item_Code_8_1 ┆ Out_of_home_qt ┆ Out_of_home_va ┆ Total_consumpt ┆ Total_consump │
│ ---           ┆ ---           ┆ y_000          ┆ lue_rs         ┆ ion_qty_000    ┆ tion_value_rs │
│ str           ┆ str           ┆ ---            ┆ ---            ┆ ---            ┆ ---           │
│               ┆               ┆ f64            ┆ f64            ┆ f64            ┆ i64           │
╞═══════════════╪═══════════════╪════════════════╪════════════════╪════════════════╪═══════════════╡
│ 46956         ┆ 331           ┆ null           ┆ null           ┆ 50.0           ┆ 200           │
│ 46956         ┆ 332           ┆ null           ┆ null           ┆ 70.0           ┆ 329           │
│ 46956         ┆ 336           ┆ null           ┆ null           ┆ 6.0            ┆ 12            │
│ 46956         ┆ 338           ┆ null           ┆ null           ┆ 10.0           ┆ 774           │
│ 46956         ┆ 346           ┆ null           ┆ null           ┆ 0.9            ┆ 135           │
│ …             ┆ …             ┆ …              ┆ …              ┆ …              ┆ …             │
│ 22451         ┆ 349           ┆ null           ┆ null           ┆ null           ┆ 1830          │
│ 22451         ┆ 349           ┆ null           ┆ null           ┆ null           ┆ 1880          │
│ 22451         ┆ 349           ┆ null           ┆ null           ┆ null           ┆ 1850          │
│ 22451         ┆ 349           ┆ null           ┆ null           ┆ null           ┆ 930           │
│ 22451         ┆ 349           ┆ null           ┆ null           ┆ null           ┆ 1110          │
└───────────────┴───────────────┴────────────────┴────────────────┴────────────────┴───────────────┘

In [15]:
idf = idf.with_columns(
    [pl.col(col).cast(pl.Int16, strict=False) for col in cols]
)
idf.schema

Schema([('FSU_Serial_No', Int16),
        ('Item_Code_8_1', Int16),
        ('Out_of_home_qty_000', Int16),
        ('Out_of_home_value_rs', Int16),
        ('Total_consumption_qty_000', Int16),
        ('Total_consumption_value_rs', Int16)])

# Save

In [16]:
print(f" {mp_data.shape[0]} are the MP data points")

 166502 are the MP data points

In [17]:
# convert to both csv and parquet data format

In [18]:
mp_data.write_csv(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-08\data2\lev_08_mp.csv")
mp_data.write_parquet(r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-08\data2\lev_08_mp.parquet", compression="zstd")
print('Save 🙌')

Save 🙌