# Goal: statistical-summary

In [13]:
""" 
Goal: statistical-summary
Author: Rudra Prasad Bhuyan
Date: 10-10-2026 14:31 IST
"""

' \nGoal: statistical-summary\nAuthor: Rudra Prasad Bhuyan\nDate: 10-10-2026 14:31 IST\n'

In [14]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
from itables import show

In [15]:
path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\parquet-data\lev-03\data\lev-03_merged.parquet"
pdf = pl.scan_parquet(path)

In [16]:
pdf.collect_schema()

Schema([('Survey_Name', String),
        ('Year', String),
        ('FSU_Serial_No', String),
        ('Sector', String),
        ('State', String),
        ('NSS_Region', String),
        ('District', String),
        ('Stratum', String),
        ('Sub_stratum', String),
        ('Panel', String),
        ('Sub_sample', String),
        ('FOD_Sub_Region', String),
        ('Sample_SU_No', String),
        ('Sample_Sub_Division_No', String),
        ('Second_Stage_Stratum_No', String),
        ('Sample_Household_No', String),
        ('Questionnaire_No', String),
        ('Level', String),
        ('HH_Size_FDQ', Float64),
        ('Engaged_in_Economic_Activity_Las', String),
        ('NCO_2015_Code', String),
        ('NIC_2008_Code', String),
        ('Max_Income_Activity', String),
        ('Self_Employment_Source_Sector', String),
        ('Regular_Wage_Source_Sector', String),
        ('Casual_Labour_Source_Sector', String),
        ('Household_Type', String),
        ('Religion_of_HH_Head', String),
        ('Social_Group_of_HH_Head', String),
        ('Land_Ownership', String),
        ('Type_of_Land_Owned', String),
        ('Total_Area_Land_Owned_Acres', String),
        ('Dwelling_Unit_Exists', String),
        ('Type_of_Dwelling_Unit', String),
        ('Energy_Source_Cooking', String),
        ('Energy_Source_Lighting', String),
        ('Ration_Card_Type', String),
        ('Rent_Rate_Available_Rural', String),
        ('Benefitted_From_PMGKY', String),
        ('Multiplier', Float64)])

# Useful Variables

In [17]:
lev_03_hh = ['HH_Size_FDQ', 'Household_Type',
            'Religion_of_HH_Head', 'Land_Ownership',
            'Type_of_Land_Owned','Total_Area_Land_Owned_Acres',
            'Energy_Source_Cooking', 'Energy_Source_Lighting',
            'Dwelling_Unit_Exists', 'Type_of_Dwelling_Unit',
            'Rent_Rate_Available_Rural', 'Multiplier']

lev_03_fin = [
    'Self_Employment_Source_Sector','Regular_Wage_Source_Sector',
    'Casual_Labour_Source_Sector', 'Ration_Card_Type']

lev_03_occupation = [
    'Engaged_in_Economic_Activity_Las',	'Max_Income_Activity']

lev_03_scheme = ['Benefitted_From_PMGKY']

lev_03_cols = (
    lev_03_hh
    + lev_03_fin
    + lev_03_occupation
    + lev_03_scheme
)

In [18]:
df = pdf.select(lev_03_cols)

In [19]:
df.head(2).collect()

shape: (2, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ HH_Size_F ┆ Household ┆ Religion_ ┆ Land_Owne ┆ … ┆ Ration_Ca ┆ Engaged_i ┆ Max_Incom ┆ Benefitt │
│ DQ        ┆ _Type     ┆ of_HH_Hea ┆ rship     ┆   ┆ rd_Type   ┆ n_Economi ┆ e_Activit ┆ ed_From_ │
│ ---       ┆ ---       ┆ d         ┆ ---       ┆   ┆ ---       ┆ c_Activit ┆ y         ┆ PMGKY    │
│ f64       ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ y_L…      ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 5.0       ┆ 2         ┆ 1         ┆ 1         ┆ … ┆ 3         ┆ 1         ┆ 1         ┆ 2        │
│ 4.0       ┆ 4         ┆ 1         ┆ 1         ┆ … ┆ 3         ┆ 1         ┆ 2         ┆ 2        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
df = df.with_columns(
    [pl.col(col).cast(pl.Int32, strict=False) for col in lev_03_cols]
)

In [21]:
unique_counts = df.select(pl.all().n_unique()).collect()
unique_counts

shape: (1, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ HH_Size_F ┆ Household ┆ Religion_ ┆ Land_Owne ┆ … ┆ Ration_Ca ┆ Engaged_i ┆ Max_Incom ┆ Benefitt │
│ DQ        ┆ _Type     ┆ of_HH_Hea ┆ rship     ┆   ┆ rd_Type   ┆ n_Economi ┆ e_Activit ┆ ed_From_ │
│ ---       ┆ ---       ┆ d         ┆ ---       ┆   ┆ ---       ┆ c_Activit ┆ y         ┆ PMGKY    │
│ u32       ┆ u32       ┆ ---       ┆ u32       ┆   ┆ u32       ┆ y_L…      ┆ ---       ┆ ---      │
│           ┆           ┆ u32       ┆           ┆   ┆           ┆ ---       ┆ u32       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 28        ┆ 7         ┆ 9         ┆ 2         ┆ … ┆ 7         ┆ 2         ┆ 4         ┆ 2        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
unique_counts = df.select(pl.all().n_unique()).collect()

categorical_cols = []
numerical_cols = []

for col in df.columns:
    if unique_counts[col][0] <13:
        categorical_cols.append(col)
    else:
        numerical_cols.append(col)

C:\Users\Rudra\AppData\Local\Temp\ipykernel_1688\3703037397.py:6: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  for col in df.columns:

In [23]:
stats = df.select(numerical_cols).describe()
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    display(stats.to_pandas().T)

,0,1,2,3,4,5,6,7,8
statistic,count,null_count,mean,std,min,25%,50%,75%,max
HH_Size_FDQ,1047812.0,0.0,4.218539,2.072699,1.0,3.0,4.0,5.0,31.0
Multiplier,1047812.0,0.0,111344.812944,79655.998345,369.0,56738.0,114044.0,150441.0,2366902.0

In [24]:
for col in categorical_cols:
    print(col)
    counts = df.select(pl.col(col).value_counts(sort=True)).collect()
    
    with pl.Config(tbl_rows=-1, tbl_cols=-1):
        display(counts.unnest(col))

Household_Type

shape: (7, 2)
┌────────────────┬────────┐
│ Household_Type ┆ count  │
│ ---            ┆ ---    │
│ i32            ┆ u32    │
╞════════════════╪════════╡
│ 1              ┆ 347200 │
│ 2              ┆ 263676 │
│ 6              ┆ 107112 │
│ 9              ┆ 103780 │
│ 4              ┆ 85312  │
│ 5              ┆ 80916  │
│ 3              ┆ 59816  │
└────────────────┴────────┘

Religion_of_HH_Head

shape: (9, 2)
┌─────────────────────┬────────┐
│ Religion_of_HH_Head ┆ count  │
│ ---                 ┆ ---    │
│ i32                 ┆ u32    │
╞═════════════════════╪════════╡
│ 1                   ┆ 812864 │
│ 2                   ┆ 125872 │
│ 3                   ┆ 69616  │
│ 4                   ┆ 16112  │
│ 6                   ┆ 11260  │
│ 9                   ┆ 9300   │
│ 5                   ┆ 2624   │
│ 0                   ┆ 144    │
│ 7                   ┆ 20     │
└─────────────────────┴────────┘

Land_Ownership

shape: (2, 2)
┌────────────────┬────────┐
│ Land_Ownership ┆ count  │
│ ---            ┆ ---    │
│ i32            ┆ u32    │
╞════════════════╪════════╡
│ 1              ┆ 976544 │
│ 2              ┆ 71268  │
└────────────────┴────────┘

Type_of_Land_Owned

shape: (4, 2)
┌────────────────────┬────────┐
│ Type_of_Land_Owned ┆ count  │
│ ---                ┆ ---    │
│ i32                ┆ u32    │
╞════════════════════╪════════╡
│ 2                  ┆ 484252 │
│ 1                  ┆ 478880 │
│ null               ┆ 71268  │
│ 3                  ┆ 13412  │
└────────────────────┴────────┘

Total_Area_Land_Owned_Acres

shape: (1, 2)
┌─────────────────────────────┬─────────┐
│ Total_Area_Land_Owned_Acres ┆ count   │
│ ---                         ┆ ---     │
│ i32                         ┆ u32     │
╞═════════════════════════════╪═════════╡
│ null                        ┆ 1047812 │
└─────────────────────────────┴─────────┘

Energy_Source_Cooking

shape: (12, 2)
┌───────────────────────┬────────┐
│ Energy_Source_Cooking ┆ count  │
│ ---                   ┆ ---    │
│ i32                   ┆ u32    │
╞═══════════════════════╪════════╡
│ 2                     ┆ 674324 │
│ 1                     ┆ 311208 │
│ 12                    ┆ 20720  │
│ 3                     ┆ 14332  │
│ 4                     ┆ 12716  │
│ 9                     ┆ 7884   │
│ 6                     ┆ 3912   │
│ 11                    ┆ 1376   │
│ 10                    ┆ 468    │
│ 7                     ┆ 428    │
│ 5                     ┆ 412    │
│ 8                     ┆ 32     │
└───────────────────────┴────────┘

Energy_Source_Lighting

shape: (7, 2)
┌────────────────────────┬─────────┐
│ Energy_Source_Lighting ┆ count   │
│ ---                    ┆ ---     │
│ i32                    ┆ u32     │
╞════════════════════════╪═════════╡
│ 1                      ┆ 1042664 │
│ 9                      ┆ 1524    │
│ 5                      ┆ 1332    │
│ 6                      ┆ 1268    │
│ 2                      ┆ 860     │
│ 3                      ┆ 156     │
│ 4                      ┆ 8       │
└────────────────────────┴─────────┘

Dwelling_Unit_Exists

shape: (2, 2)
┌──────────────────────┬─────────┐
│ Dwelling_Unit_Exists ┆ count   │
│ ---                  ┆ ---     │
│ i32                  ┆ u32     │
╞══════════════════════╪═════════╡
│ 1                    ┆ 1041448 │
│ 2                    ┆ 6364    │
└──────────────────────┴─────────┘

Type_of_Dwelling_Unit

shape: (4, 2)
┌───────────────────────┬────────┐
│ Type_of_Dwelling_Unit ┆ count  │
│ ---                   ┆ ---    │
│ i32                   ┆ u32    │
╞═══════════════════════╪════════╡
│ 1                     ┆ 875868 │
│ 2                     ┆ 146468 │
│ 3                     ┆ 19112  │
│ null                  ┆ 6364   │
└───────────────────────┴────────┘

Rent_Rate_Available_Rural

shape: (3, 2)
┌───────────────────────────┬────────┐
│ Rent_Rate_Available_Rural ┆ count  │
│ ---                       ┆ ---    │
│ i32                       ┆ u32    │
╞═══════════════════════════╪════════╡
│ 2                         ┆ 462600 │
│ null                      ┆ 430384 │
│ 1                         ┆ 154828 │
└───────────────────────────┴────────┘

Self_Employment_Source_Sector

shape: (3, 2)
┌───────────────────────────────┬────────┐
│ Self_Employment_Source_Sector ┆ count  │
│ ---                           ┆ ---    │
│ i32                           ┆ u32    │
╞═══════════════════════════════╪════════╡
│ null                          ┆ 755892 │
│ 1                             ┆ 200328 │
│ 2                             ┆ 91592  │
└───────────────────────────────┴────────┘

Regular_Wage_Source_Sector

shape: (3, 2)
┌────────────────────────────┬────────┐
│ Regular_Wage_Source_Sector ┆ count  │
│ ---                        ┆ ---    │
│ i32                        ┆ u32    │
╞════════════════════════════╪════════╡
│ null                       ┆ 956036 │
│ 4                          ┆ 85312  │
│ 3                          ┆ 6464   │
└────────────────────────────┴────────┘

Casual_Labour_Source_Sector

shape: (3, 2)
┌─────────────────────────────┬────────┐
│ Casual_Labour_Source_Sector ┆ count  │
│ ---                         ┆ ---    │
│ i32                         ┆ u32    │
╞═════════════════════════════╪════════╡
│ null                        ┆ 859784 │
│ 6                           ┆ 107112 │
│ 5                           ┆ 80916  │
└─────────────────────────────┴────────┘

Ration_Card_Type

shape: (7, 2)
┌──────────────────┬────────┐
│ Ration_Card_Type ┆ count  │
│ ---              ┆ ---    │
│ i32              ┆ u32    │
╞══════════════════╪════════╡
│ 4                ┆ 325476 │
│ 2                ┆ 231744 │
│ 0                ┆ 205440 │
│ 3                ┆ 159612 │
│ 1                ┆ 50344  │
│ 9                ┆ 39544  │
│ 5                ┆ 35652  │
└──────────────────┴────────┘

Engaged_in_Economic_Activity_Las

shape: (2, 2)
┌─────────────────────────────────┬────────┐
│ Engaged_in_Economic_Activity_L… ┆ count  │
│ ---                             ┆ ---    │
│ i32                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ 1                               ┆ 944032 │
│ 2                               ┆ 103780 │
└─────────────────────────────────┴────────┘

Max_Income_Activity

shape: (4, 2)
┌─────────────────────┬────────┐
│ Max_Income_Activity ┆ count  │
│ ---                 ┆ ---    │
│ i32                 ┆ u32    │
╞═════════════════════╪════════╡
│ 1                   ┆ 438792 │
│ 2                   ┆ 263860 │
│ 3                   ┆ 241380 │
│ null                ┆ 103780 │
└─────────────────────┴────────┘

Benefitted_From_PMGKY

shape: (2, 2)
┌───────────────────────┬────────┐
│ Benefitted_From_PMGKY ┆ count  │
│ ---                   ┆ ---    │
│ i32                   ┆ u32    │
╞═══════════════════════╪════════╡
│ 1                     ┆ 539012 │
│ 2                     ┆ 508800 │
└───────────────────────┴────────┘