In [1]:
import polars as pl
import pandas as pd

In [ ]:
# raw_file_path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\delete\raw-data\LEVEL - 14 (Section  A1,B1 & C1).dta"

In [ ]:
csv_file_path = 'raw_level_14.csv'

# Read the .dta file into a pandas DataFrame
pandas_df = pd.read_stata()

In [ ]:
polars_df = pl.from_pandas(pandas_df)

In [32]:
# Write to .csv file with polars
polars_df.write_csv(csv_file_path)

In [6]:
raw_csv_file_path = r"C:\Users\Rudra\Desktop\rural-financial-inclusion-govt-scheme-recommendation\sql-scripts\insert-data-into-db\L-14\raw_level_14.csv"

In [7]:
polars_df = pl.read_csv(raw_csv_file_path)

In [8]:
df = pd.read_csv(raw_csv_file_path, encoding="ISO-8859-1",)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8296569 entries, 0 to 8296568
Data columns (total 22 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Survey_Name              object
 1   Year                     int64
 2   FSU_Serial_No            int64
 3   Sector                   int64
 4   State                    int64
 5   NSS_Region               int64
 6   District                 int64
 7   Stratum                  int64
 8   Sub_stratum              int64
 9   Panel                    int64
 10  Sub_sample               int64
 11  FOD_Sub_Region           int64
 12  Sample_SU_No             int64
 13  Sample_Sub_Division_No   float64
 14  Second_Stage_Stratum_No  int64
 15  Sample_Household_No      int64
 16  Questionnaire_No         object
 17  Level                    int64
 18  SECTION                  float64
 19  ITEM_CODE                int64
 20  VALUE_RS                 int64
 21  MULTIPLIER               int64
dtypes: float64(2), int64(18), object(2)
memory usage: 1.4+ GB

In [10]:
df.columns

Index(['Survey_Name', 'Year', 'FSU_Serial_No', 'Sector', 'State', 'NSS_Region',
       'District', 'Stratum', 'Sub_stratum', 'Panel', 'Sub_sample',
       'FOD_Sub_Region', 'Sample_SU_No', 'Sample_Sub_Division_No',
       'Second_Stage_Stratum_No', 'Sample_Household_No', 'Questionnaire_No',
       'Level', 'SECTION', 'ITEM_CODE', 'VALUE_RS', 'MULTIPLIER'],
      dtype='object')

In [11]:
df.shape

(8296569, 22)

In [12]:
df.sample(5)

,Survey_Name,Year,FSU_Serial_No,Sector,State,NSS_Region,District,Stratum,Sub_stratum,Panel,...,Sample_SU_No,Sample_Sub_Division_No,Second_Stage_Stratum_No,Sample_Household_No,Questionnaire_No,Level,SECTION,ITEM_CODE,VALUE_RS,MULTIPLIER
6906196,HCES,2024,47114,1,9,91,5,23,47,6,...,11,NaN,3,8,D,13,14.6,579,408,139956
1193918,HCES,2024,49545,1,18,181,14,23,3,3,...,2,NaN,3,11,F,5,6.7,269,75,87779
7644851,HCES,2024,44166,1,23,235,32,23,15,9,...,2,NaN,3,8,D,13,14.2,609,3000,155064
1194447,HCES,2024,49542,1,18,184,26,23,3,6,...,1,NaN,3,10,F,5,6.5,199,200,143548
6240914,HCES,2024,44263,1,21,213,5,23,10,9,...,2,NaN,3,4,D,12,13.2,399,2600,143220

In [13]:
df[['SECTION', 'ITEM_CODE', 'VALUE_RS', 'MULTIPLIER']].sample(5)

         SECTION  ITEM_CODE  VALUE_RS  MULTIPLIER
263656       6.6        189       144      105944
8229240     14.6        579      1500      222751
5743859     12.2        319       100      133523
7120410     14.1        649       220      126490
2406494      5.3        179        96      121607

In [16]:
df['ITEM_CODE'].unique()

array([139, 129, 159, 169, 179, 189, 199, 219, 239, 249, 269, 279, 289,
       299, 349, 899, 539, 409, 429, 439, 459, 479, 499, 519, 419, 529,
       329, 319, 309, 379, 389, 399, 559, 579, 599, 609, 629, 639, 649,
        99, 569, 619], dtype=int64)

In [15]:
df['SECTION'].unique()

array([ 5.1,  5.2,  6.1,  5.3,  6.6,  6.5,  6.2,  6.3,  6.4,  6.7,  6.8,
        7.1,  7.2,  8.1, 11.4, 10.1, 10.3, 11.3,  9.1,  9.2, 11.2, 11.1,
       10.2, 12.3, 12.2, 12.1, 13.1, 13.3, 13.2, 14.7, 14.6, 14.5, 14.2,
       14.1, 14.9, 14.3, 14.8, 14.4])

In [ ]:
df['VALUE_RS'].describe()

count    8.296569e+06
mean     2.076884e+03
std      1.011308e+04
min      0.000000e+00
25%      1.600000e+02
50%      4.420000e+02
75%      1.300000e+03
max      4.511750e+06
Name: VALUE_RS, dtype: float64

In [ ]:
df.isnull().sum()

Survey_Name                      0
Year                             0
FSU_Serial_No                    0
Sector                           0
State                            0
NSS_Region                       0
District                         0
Stratum                          0
Sub_stratum                      0
Panel                            0
Sub_sample                       0
FOD_Sub_Region                   0
Sample_SU_No                     0
Sample_Sub_Division_No     8231454
Second_Stage_Stratum_No          0
Sample_Household_No              0
Questionnaire_No                 0
Level                            0
SECTION                          0
ITEM_CODE                        0
VALUE_RS                         0
MULTIPLIER                       0
dtype: int64

In [ ]:
df.head().to_csv("test-L14.csv", index=False)